export const headlineOptions = [
  "Animal Trainer",
  "Appliance Repair",
  "Appliance Technician",
  "Artist",
  "Athletic Trainer",
  "Athletic Trainers",
  "Auto Mechanic",
  "Auto Repair",
  "Barber",
  "Barber & Hair Stylist",
  "Barber Stylist",
  "Bartender",
  "Beauty Artist",
  "Bicycle Repairers",
  "Bike Mechanic",
  "Brow Artist",
  "Brow Technician",
  "Car Mechanic",
  "Carpenter",
  "Carpentry",
  "Carpet Cleaner",
  "Carpet Installer",
  "Carpet Installers",
  "Chef",
  "Cleaner",
  "Coach",
  "Craft Artist",
  "Craft Artists",
  "Dance Instructor",
  "DJ",
  "Drum Teacher",
  "Electrician",
  "Electrician Services",
  "Event Lighting",
  "Event Photographer",
  "Event Videographer",
  "Eyelash Extension Specialist",
  "Fitness Trainer",
  "Gardener",
  "General Repair",
  "Guitar Teacher",
  "Hair Stylist",
  "Hair Stylist & Colorist",
  "Hairdresser",
  "Handyman",
  "Home Tutor",
  "House Cleaner",
  "House Cleaning",
  "House Painter",
  "Housekeeper",
  "Instructor",
  "Janitors & Cleaners",
  "Landscaper",
  "Lash Artist",
  "Lash Technician",
  "Lawn Care",
  "Lighting Technician",
  "Lighting Technicians",
  "Live Music",
  "Locksmith",
  "Locksmiths & Safe Repairers",
  "Maid",
  "Maids & Housekeeping Cleaners",
  "Maintenance & Repair Workers",
  "Makeup Artist",
  "Makeup Stylist",
  "Manicurist",
  "Massage Therapist",
  "Meal Prep Chef",
  "Mechanic",
  "Music Teacher",
  "Musician",
  "Musicians & Singers",
  "Nail Artist",
  "Nail Technician",
  "Painter",
  "Painter & Artist",
  "Pedicurist",
  "Personal Chef",
  "Personal Trainer",
  "Photographer",
  "Piano Teacher",
  "Pilates Instructor",
  "Plumber",
  "Plumbing",
  "Portrait Photographer",
  "Private Chef",
  "Private Coach",
  "Private Tutor",
  "Roofer",
  "Roofing",
  "Singer",
  "Ski Instructor",
  "Sports Coach",
  "Sports Massage Therapist",
  "Swim Instructor",
  "Tutor",
  "Video Creator",
  "Videographer",
  "Voice Coach",
  "Watch & Clock Repairers",
  "Watch Repair",
  "Waxing Specialist",
  "Workshop Instructor",
  "Yard Work",
  "Yoga Instructor",
];
