export const headlineOptions = [
  "Animal Trainer",
  "Appliance Repair",
  "Artists & Related Workers",
  "Athletes & Sports Competitors",
  "Athletic Trainers",
  "Avionics Technicians",
  "Barber",
  "Bartender",
  "Bicycle Repairers",
  "Broadcast Technicians",
  "Bus Drivers",
  "Carpenter",
  "Carpet Installers",
  "Chef",
  "Coaches & Scouts",
  "Counselors",
  "Craft Artists",
  "Delivery Driver",
  "Dietetic Technicians",
  "Dietitians & Nutritionists",
  "Driver",
  "Electrician",
  "Emergency Medical Technicians",
  "Fine Artists",
  "Genetic Counselors",
  "Hair Stylist",
  "Janitors & Cleaners",
  "Kindergarten Teachers",
  "Landscaper",
  "Library Technicians",
  "Lighting Technicians",
  "Locksmiths & Safe Repairers",
  "Maids & Housekeeping Cleaners",
  "Maintenance & Repair Workers",
  "Makeup Artist",
  "Marriage & Family Therapists",
  "Mechanic",
  "Mechanical Door Repairers",
  "Medical Equipment Repairers",
  "Musicians & Singers",
  "Ophthalmic Medical Technicians",
  "Painter",
  "Pharmacy Technicians",
  "Photographer",
  "Plumber",
  "Private Driver",
  "Psychiatric Technicians",
  "Radiation Therapists",
  "Rail Car Repairers",
  "Recreational Therapists",
  "Refractory Materials Repairers",
  "Rehabilitation Counselors",
  "Respiratory Therapists",
  "Roofer",
  "Security Guard",
  "Therapists",
  "Tire Repairers & Changers",
  "Traffic Technicians",
  "Tutor",
  "Videographer",
  "Watch & Clock Repairers",
  "Workshop Instructor",
];
